### ISSUE TITLE
No Lock Status

### ISSUE THREAD

**Issue by pug306d** [yp87/leaf2mqtt#11]
Hi,

I cannot see in the documentation if it’s possible to see the lock status of the car? If not could you add it? The Nissan Connect app shows the status so should be possible?

Thanks!

**Comment by yp87** [comment]
Hello!
The communication with the Nissan API is using the libraries from https://github.com/Tobiaswk.
Unfortunately, those libraries does not support door lock status. 
You can ask the author to add this feature to his app "My Leaf" and I will be able to add the feature once it is available in the libraries.

However, I don't see the door lock status in the official Nissan Leaf app. Only the door lock and unlock actions.

Regards

**Comment by yp87** [comment]
I will close this issue for now.

**Comment by pug306d** [comment]
![0ED8307C-FC3A-4931-88BB-3336DD578307](https://user-images.githubusercontent.com/1840059/144372769-bcf6e2a9-a124-4c9e-a20d-648cbe365f01.jpeg)

In the Nissan Connect App on mine the lock status is shown if you select … on the first page.

which project do you use from Tobiaswk and I’ll open a request there to support it?

thanks!
