### ISSUE TITLE
update cabintempC

### ISSUE THREAD

**Issue by ptitbasou** [yp87/leaf2mqtt#13]
Hello, thanks for your work.
I'am french and use it for my leaf 2 - 2018. It's work for all except for cabintemp update.
If i use command/climate | update, the lastReceivedDateTimeUtc change but not the cabinTemperatureC or cabinTemperatureF.

However, if i open the app Nisan EV on my phone and check cabintemp, if after i update mqtt command/climate, cabinTemperatureC respons is update with the rigth value.

Have you and idea why ?

**Comment by yp87** [comment]
Bonjour 😀

Je ne suis pas trop certain si tu es en Europe ou au Canada, Alors quelques questions pour toi:

Si tu utilises le `LEAF_TYPE` `olderCanada`, Je viens tout juste de l'ajouter, par contre, la valeur ne sera pas mise à jour souvent (même avec une commande update) dû à la façon que l'api de Nissan fonctionne et dû au design de leaf2mqtt. Je vais trouver une meilleur solution quand j'aurai un peu plus de temps. 

Si tu utilises le `LEAF_TYPE` `olderEurope`:
1) Est-ce que tu reçois le `RunningStatus` en même temps que le `lastReceivedDateTimeUtc`?
2) Si tu essaies avec l'application `My Leaf`, est-ce que ça fonctionne?

Sinon, quel `LEAF_TYPE` utilises-tu?

Merci!

**Comment by ptitbasou** [comment]
Bonjour,
Je suis en Europe, france. J'utilise LEAF_TYPE olderEurope, oui je reçois en même temps le RunningStatus et lastReceivedDateTimeUtc.
Je n'ai pas l'app My Leaf j'utilisais justement ton travail pour récupérer les données sous jeedom.
J'ai refais un test:
climate/lastReceivedDateTimeUtcQoS: 0
2021-12-17T12:55:49.866882Z
/climate/cabinTemperatureCQoS: 0
12.5

Et 30 min après:
/climate/lastReceivedDateTimeUtcQoS: 0
2021-12-17T13:24:32.939898Z
/climate/cabinTemperatureCQoS: 0
12.5

Alors que le chauffage est allumé dans la voiture depuis tout ce temps...

**Comment by yp87** [comment]
Bonjour, 
J'ai changé la façon avec laquelle je vais chercher la température pour cette api.
Est-ce que tu peux réessayer avec la dernière version du conteneur svp?
yp87/leaf2mqtt:18

Merci!

**Comment by ptitbasou** [comment]
**Super, ça fonctionne merci beaucoup!!**
Par contre, cette commande ne fonctionne pas chez moi: 
topic: leaf/SJNFAAZE1U00XXXXX/command 
valeur: update
Elle ne rafraichie pas l'ensemble des statuts battery et climate. Ce n'est pas grave, je passe du coup par les commandes détaillées, 1 pour battery et l'autre pour climate.
Je vais maintenant tester pour les statistiques.
Merci

**Comment by yp87** [comment]
Tant mieux pour la température!

Pour la commande update, elle devrait combiner la même logique que les commandes détaillées. Ça semble fonctionner de mon bord.
Entre-autre pour la batterie, il est conseillé de faire plusieurs appels jusqu'à ce que battery/lastUpdatedDateTimeUtc soit moins de 10 minutes dans le passé.
Tu peux regarder mes scripts avec Home Assistant: 
update_leaf_battery ici: https://github.com/yp87/HomeAssistant/blob/master/hass/script/cars/leaf.yaml

Puisque le problème original est réglé, je vais fermer cette issue.
Merci!
