### ISSUE TITLE
An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.

### ISSUE THREAD

**Issue by zekje** [yp87/leaf2mqtt#14]
HI, i have tried with my European Leaf 40 2018, but i have got the error  : 
An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.

i am sure of my username and password ( i just tried Nissan official site and it's ok )
i hav tried all choice between newerThanMay2019, olderCanada, olderUSA, olderEurope, olderAustralia or olderJapan ( i think i need to use olderEurope ) , but it doesn't work .

with loglevel to info : 
SEVERE: 2021-12-25 20:12:30.188255: main: V0.10
INFO: 2021-12-25 20:12:30.188749: MqttClientWrapper: Creating MQTT client with 192.168.0.201:1883 listening on leaf.
INFO: 2021-12-25 20:12:30.189830: MqttClientWrapper: Connecting...
INFO: 2021-12-25 20:12:30.199924: MqttClientWrapper: Mqtt connection code: MqttConnectReturnCode.connectionAccepted
INFO: 2021-12-25 20:12:30.200021: main: Logging in.
WARNING: 2021-12-25 20:12:32.205375: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
WARNING: 2021-12-25 20:12:32.205944: main: Could not execute request.

**Comment by 1onord** [comment]
+1 

i have the same Problem, but a few weeks ago i got an Answer from the Interface....

WARNING: 2021-12-29 15:43:39.717284: main: An error occured while logging in. Please make sure you have selected the right LEAF_TY
PE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.                                                                       
WARNING: 2021-12-29 15:43:39.717324: main: Could not execute request.

**Comment by yp87** [comment]
The maintainer of the DartCarwings api added user agent support. Maybe it is the fix you need. I updated the dependency, please try again.
Thank you!

**Comment by 1onord** [comment]
Hey, 

you made my Day, for me it works now. Good Work !

<img width="310" alt="jdjdhd" src="https://user-images.githubusercontent.com/77094944/147859124-ff0b05ce-8307-4ca5-8d4a-679284705ad1.png">

**Comment by yp87** [comment]
Just updated a dependency :) (https://gitlab.com/tobiaswkjeldsen/dartcarwings)

**Comment by F13** [comment]
I'm getting this same issue, using the provided docker image. Any troubleshooting steps you'd recommend?

**Comment by yp87** [comment]
@F13  Please provide location and leaf model year.

**Comment by F13** [comment]
I have a 2018 leaf in the US. It looks like something may have happened to
the API, though - the My Leaf app has a notification:

```
27. Jan - To all North American users; Nissan has blocked My Leaf and
others clients! We urge you to email ***@***.***
with complaints!
```

So, not much you can do. This should be fun 🙄

**Comment by F13** [comment]
I have a 2018 leaf in the US. It looks like something may have happened to the API, though - the My Leaf app has a notification:

> 27. Jan - To all North American users; Nissan has blocked My Leaf and others clients! We urge you to email nissanownerservices@nissan-usa.com with complaints!

So, not much you can do. This should be fun 🙄

**Comment by yp87** [comment]
The key was updated and work again. We found a way to dynamically fetch the key from the same place as of the official app. Once this is added in the NissanConnectNA library, the key will be updated in real time, until Nissan also break this.

**Comment by F13** [comment]
I'm not sure I follow. On the newest release I'm still getting the same error. Are you saying you found an API key that is not yet, but will be, accepted by the Nissan API?

**Comment by yp87** [comment]
Are you able to login with the newest MyLeaf app?

**Comment by F13** [comment]
I recreated the container twice and now it logs in successfully ¯\\\_(ツ)_/¯

Sorry for the trouble!
