### ISSUE TITLE
WARNING: main: Could not execute request.

### ISSUE THREAD

**Issue by zekje** [yp87/leaf2mqtt#20]
Hi, i ll try again to use leaf2mqtt and it's not ok for me

i use Armbian 21.08.6 Bullseye with Linux 5.4.160-odroidxu4  on odroid XU4
Docker version 20.10.11, build dea9396

to compile leaf2 mqqt , "docker build -tag leaf2mqtt ." will not work, i need to use "docker build -t leaf2mqtt ." instead

when i launch by "
docker run --restart always -e LEAF_USERNAME="mymail" -e LEAF_PASSWORD="mypassword" -e LEAF_TYPE="olderEurope" -e MQTT_HOST=192.168.0.201 -e UPDATE_INTERVAL_MINUTES=30 -e COMMAND_ATTEMPTS=5 --name leaf2mqtt 
"

i have on the console : 
SEVERE: 2022-01-04 17:29:04.313335: main: V0.10
WARNING: 2022-01-04 17:29:23.371647: main: Could not execute request.

on my mqtt i have this : 
>leaf
lastErrorDateTimeUtc = 2022-01-03T17:11:09.330354Z 
and nothing else

where i am wrong ?
( i am a beginner on docker :p )

**Comment by yp87** [comment]
Hello!
Can you set the `LOG_LEVEL` to `FINEST` and send the new logs please.
Add this option along the others in your docker run command.

**Comment by zekje** [comment]
hi, this is the loglevel finest , i just rempla my leaf name and vin .

`SEVERE: 2022-01-06 12:20:44.738521: main: V0.10
INFO: 2022-01-06 12:20:44.739646: MqttClientWrapper: Creating MQTT client with 192.168.0.201:1883 listening on leaf.
INFO: 2022-01-06 12:20:44.743659: MqttClientWrapper: Connecting...
INFO: 2022-01-06 12:20:44.763244: MqttClientWrapper: Mqtt connection code: MqttConnectReturnCode.connectionAccepted
INFO: 2022-01-06 12:20:44.764374: main: Logging in.
INFO: 2022-01-06 12:20:53.447587: main: Login successful
INFO: 2022-01-06 12:20:53.447662: main: MQTT connected.
INFO: 2022-01-06 12:20:53.447719: MqttClientWrapper: Subscribing to command topics
FINEST: 2022-01-06 12:20:53.448284: main: publishStates {nickname: LEAF, vin: SJNFAAZE1XXXXXXXX, SJNFAAZE1XXXXXXXX/nickname: LEAF, SJNFAAZE1XXXXXXXX/vin: SJNFAAZE1XXXXXXXX}
FINEST: 2022-01-06 12:20:53.448339: MqttClientWrapper: Publishing message nickname LEAF
FINEST: 2022-01-06 12:20:53.448537: MqttClientWrapper: Publishing message vin SJNFAAZE1XXXXXXXX
FINEST: 2022-01-06 12:20:53.448746: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/nickname LEAF
FINEST: 2022-01-06 12:20:53.448920: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/vin SJNFAAZE1XXXXXXXX
INFO: 2022-01-06 12:20:53.449138: main: Starting loop for SJNFAAZE1XXXXXXXX
INFO: 2022-01-06 12:20:53.449200: main: Subscribing to commands for SJNFAAZE1XXXXXXXX
FINE: 2022-01-06 12:20:53.449240: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command
FINE: 2022-01-06 12:20:53.449339: MqttClientWrapper: Subscribing to command
FINE: 2022-01-06 12:20:53.449387: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command/battery
FINE: 2022-01-06 12:20:53.449440: MqttClientWrapper: Subscribing to command/battery
FINE: 2022-01-06 12:20:53.449477: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command/climate
FINE: 2022-01-06 12:20:53.449524: MqttClientWrapper: Subscribing to command/climate
FINE: 2022-01-06 12:20:53.449560: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command/stats/daily
FINE: 2022-01-06 12:20:53.449611: MqttClientWrapper: Subscribing to command/stats/daily
FINE: 2022-01-06 12:20:53.449646: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command/stats/monthly
FINE: 2022-01-06 12:20:53.449682: MqttClientWrapper: Subscribing to command/stats/monthly
FINE: 2022-01-06 12:20:53.449731: MqttClientWrapper: Subscribing to SJNFAAZE1XXXXXXXX/command/location
FINE: 2022-01-06 12:20:53.449766: MqttClientWrapper: Subscribing to command/location
FINER: 2022-01-06 12:20:53.449805: main: fetchAndPublishAllStatus for SJNFAAZE1XXXXXXXX
FINER: 2022-01-06 12:20:53.449865: main: fetchAndPublishBatteryStatus for SJNFAAZE1XXXXXXXX
FINEST: 2022-01-06 12:20:53.449946: LeafSession: Executing
FINER: 2022-01-06 12:20:53.450713: main: fetchAndPublishClimateStatus for SJNFAAZE1XXXXXXXX
FINEST: 2022-01-06 12:20:53.450765: LeafSession: Executing
FINER: 2022-01-06 12:20:53.451501: main: fetchAndPublishLocation for SJNFAAZE1XXXXXXXX
FINEST: 2022-01-06 12:20:53.451565: LeafSession: Executing
FINEST: 2022-01-06 12:20:53.453355: main: publishStates {nickname: LEAF, vin: SJNFAAZE1XXXXXXXX}
FINEST: 2022-01-06 12:20:53.453420: MqttClientWrapper: Publishing message nickname LEAF
FINEST: 2022-01-06 12:20:53.453683: MqttClientWrapper: Publishing message vin SJNFAAZE1XXXXXXXX
FINE: 2022-01-06 12:20:54.474846: LeafSession: FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

FINER: 2022-01-06 12:20:54.475180: LeafSession: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40)
#4      JsonDecoder.convert (dart:convert/json.dart:506)
#5      JsonCodec.decode (dart:convert/json.dart:157)
#6      CarwingsSession.request (package:dartcarwings/src/carwings_session.dart:72)
<asynchronous suspension>
#7      CarwingsSession.requestWithRetry (package:dartcarwings/src/carwings_session.dart:46)
<asynchronous suspension>
#8      CarwingsVehicle.requestLocation (package:dartcarwings/src/carwings_vehicle.dart:355)
<asynchronous suspension>
#9      CarwingsVehicleWrapper.fetchLocation (file:///app/src/leaf/carwings_wrapper.dart:110)
<asynchronous suspension>
#10     LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#11     LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#13     startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#14     Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#15     main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINER: 2022-01-06 12:20:54.475233: LeafSession: Force a login before retrying failed execution.
FINEST: 2022-01-06 12:20:55.183248: main: publishStates {battery/percentage: 50, battery/connected: true, battery/charging: false, battery/capacity: 240.0, battery/cruisingRangeAcOffKm: 114, battery/cruisingRangeAcOffMiles: 71, battery/cruisingRangeAcOnKm: 109, battery/cruisingRangeAcOnMiles: 68, battery/lastUpdatedDateTimeUtc: 2022-01-05T17:46:00.000Z, battery/timeToFullL2InMinutes: 390, battery/timeToFullL2_6kwInMinutes: 390, battery/timeToFullTrickleInMinutes: 1230, battery/lastReceivedDateTimeUtc: 2022-01-06T12:20:55.183060Z, SJNFAAZE1XXXXXXXX/battery/percentage: 50, SJNFAAZE1XXXXXXXX/battery/connected: true, SJNFAAZE1XXXXXXXX/battery/charging: false, SJNFAAZE1XXXXXXXX/battery/capacity: 240.0, SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOffKm: 114, SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOffMiles: 71, SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOnKm: 109, SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOnMiles: 68, SJNFAAZE1XXXXXXXX/battery/lastUpdatedDateTimeUtc: 2022-01-05T17:46:00.000Z, SJNFAAZE1XXXXXXXX/battery/timeToFullL2InMinutes: 390, SJNFAAZE1XXXXXXXX/battery/timeToFullL2_6kwInMinutes: 390, SJNFAAZE1XXXXXXXX/battery/timeToFullTrickleInMinutes: 1230, SJNFAAZE1XXXXXXXX/battery/lastReceivedDateTimeUtc: 2022-01-06T12:20:55.183060Z}
FINEST: 2022-01-06 12:20:55.183330: MqttClientWrapper: Publishing message battery/percentage 50
FINEST: 2022-01-06 12:20:55.185044: MqttClientWrapper: Publishing message battery/connected true
FINEST: 2022-01-06 12:20:55.185337: MqttClientWrapper: Publishing message battery/charging false
FINEST: 2022-01-06 12:20:55.185509: MqttClientWrapper: Publishing message battery/capacity 240.0
FINEST: 2022-01-06 12:20:55.185629: MqttClientWrapper: Publishing message battery/cruisingRangeAcOffKm 114
FINEST: 2022-01-06 12:20:55.185776: MqttClientWrapper: Publishing message battery/cruisingRangeAcOffMiles 71
FINEST: 2022-01-06 12:20:55.185921: MqttClientWrapper: Publishing message battery/cruisingRangeAcOnKm 109
FINEST: 2022-01-06 12:20:55.186253: MqttClientWrapper: Publishing message battery/cruisingRangeAcOnMiles 68
FINEST: 2022-01-06 12:20:55.186397: MqttClientWrapper: Publishing message battery/lastUpdatedDateTimeUtc 2022-01-05T17:46:00.000Z
FINEST: 2022-01-06 12:20:55.186563: MqttClientWrapper: Publishing message battery/timeToFullL2InMinutes 390
FINEST: 2022-01-06 12:20:55.186690: MqttClientWrapper: Publishing message battery/timeToFullL2_6kwInMinutes 390
FINEST: 2022-01-06 12:20:55.186951: MqttClientWrapper: Publishing message battery/timeToFullTrickleInMinutes 1230
FINEST: 2022-01-06 12:20:55.187103: MqttClientWrapper: Publishing message battery/lastReceivedDateTimeUtc 2022-01-06T12:20:55.183060Z
FINEST: 2022-01-06 12:20:55.187367: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/percentage 50
FINEST: 2022-01-06 12:20:55.187735: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/connected true
FINEST: 2022-01-06 12:20:55.188029: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/charging false
FINEST: 2022-01-06 12:20:55.188148: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/capacity 240.0
FINEST: 2022-01-06 12:20:55.188364: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOffKm 114
FINEST: 2022-01-06 12:20:55.188587: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOffMiles 71
FINEST: 2022-01-06 12:20:55.188742: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOnKm 109
FINEST: 2022-01-06 12:20:55.188991: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/cruisingRangeAcOnMiles 68
FINEST: 2022-01-06 12:20:55.189327: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/lastUpdatedDateTimeUtc 2022-01-05T17:46:00.000Z
FINEST: 2022-01-06 12:20:55.189503: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/timeToFullL2InMinutes 390
FINEST: 2022-01-06 12:20:55.189648: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/timeToFullL2_6kwInMinutes 390
FINEST: 2022-01-06 12:20:55.189797: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/timeToFullTrickleInMinutes 1230
FINEST: 2022-01-06 12:20:55.189962: MqttClientWrapper: Publishing message SJNFAAZE1XXXXXXXX/battery/lastReceivedDateTimeUtc 2022-01-06T12:20:55.183060Z
FINEST: 2022-01-06 12:21:02.662452: LeafSession: Executing
FINE: 2022-01-06 12:21:03.687944: LeafSession: FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

FINER: 2022-01-06 12:21:03.688186: LeafSession: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40)
#4      JsonDecoder.convert (dart:convert/json.dart:506)
#5      JsonCodec.decode (dart:convert/json.dart:157)
#6      CarwingsSession.request (package:dartcarwings/src/carwings_session.dart:72)
<asynchronous suspension>
#7      CarwingsSession.requestWithRetry (package:dartcarwings/src/carwings_session.dart:46)
<asynchronous suspension>
#8      CarwingsVehicle.requestLocation (package:dartcarwings/src/carwings_vehicle.dart:355)
<asynchronous suspension>
#9      CarwingsVehicleWrapper.fetchLocation (file:///app/src/leaf/carwings_wrapper.dart:110)
<asynchronous suspension>
#10     LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#11     LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#13     startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#14     Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#15     main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINE: 2022-01-06 12:21:03.688333: LeafSession: Exception: Execution failed.
FINER: 2022-01-06 12:21:03.688438: LeafSession: #0      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:161)
<asynchronous suspension>
#1      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#3      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#5      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

WARNING: 2022-01-06 12:21:03.688482: main: Could not execute request.
FINEST: 2022-01-06 12:21:03.688561: MqttClientWrapper: Publishing message lastErrorDateTimeUtc 2022-01-06T12:21:03.688533Z
FINEST: 2022-01-06 12:21:03.688798: MqttClientWrapper: Publishing message {vin}/lastErrorDateTimeUtc 2022-01-06T12:21:03.688533Z
FINE: 2022-01-06 12:21:14.380113: LeafSession: Error
FINER: 2022-01-06 12:21:14.380664: LeafSession: #0      CarwingsVehicle.responseFlagHandler (package:dartcarwings/src/carwings_vehicle.dart:398)
#1      CarwingsVehicle._getCabinTemperature (package:dartcarwings/src/carwings_vehicle.dart:332)
<asynchronous suspension>
#2      CarwingsVehicle.requestCabinTemperature (package:dartcarwings/src/carwings_vehicle.dart:311)
<asynchronous suspension>
#3      CarwingsVehicleWrapper.fetchClimateStatus (file:///app/src/leaf/carwings_wrapper.dart:87)
<asynchronous suspension>
#4      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#5      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#7      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:473)
<asynchronous suspension>
#9      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINER: 2022-01-06 12:21:14.380743: LeafSession: Force a login before retrying failed execution.
FINEST: 2022-01-06 12:21:22.956817: LeafSession: Executing
`

**Comment by yp87** [comment]
So what I understand is there is an issue in the parsing of the gps location response. But everything else should still work.
The location will be queried at the startup of the container, then it will only be queried when calling `command update`
or `command/location update`.
But it should not impact anything else.
In your log, we see that other info like battery % is correctly published to your mqtt broker.

If you do not need to use the location, you can close this issue now as everything else seems to be working (you can ignore the warning at the startup)

If you want to use the location, I would need the content of the response. To get this, you have to update to the latest version of leaf2mqtt. This update will output the nissan carwing api library logs alongs the other logs.
⚠️ **Make sure to sanitize those logs since it will contain your username and password.**

**Comment by yp87** [comment]
I will close this issue for now. Please re-open if needed
