### ISSUE TITLE
Additional data available

### ISSUE THREAD

**Issue by sensor-freak** [yp87/leaf2mqtt#23]
Is the total km/miles counter available from the Nissan API? If so, can the value be added to the MQTT output?

And also: some items from the battery structure (`timeToFullL2_6kwInMinutes`, `timeToFullTrickleInMinutes`) are not contained in the `battery/json` topic. Might that be added sometime?

Thank you for the great work!

**Comment by yp87** [comment]
Hello @sensor-freak,

The total km/miles couter is not available from the libraries I use to access the Nissan API. Only the monthly or daily stats is available.

As for the `timeToFullL2_6kwInMinutes` and `timeToFullTrickleInMinutes`, it will only be present if the value is not 0. I guess 0 make sense if the car is already full. Do you see the value if your car is not full? If no then I suspect the api to return a value of 0.

I don't mind keeping the value 0 if it makes more sense for you.

**Comment by sensor-freak** [comment]
Hi @yp87,

thank you for the response. In the meantime I have done some work on the dartnissanconnect library to add cockpit status to the library, which essentially contains the mileage value (see [tobiaswkjeldsen/dartnissanconnect#3](https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/issues/3)). However, the implementation changes only one of the three libraries, the merge request is not yet merged, and that MR is not on GitHub, but on GitLab. If you like, I could provide the MR also on GitHub.

Regarding the `timeToFullxxx` values I would prefer to keep the 0 values in the results. I'm using the mqtt_consumer input plugin with telegraf for post-processing the published values from `leaf2mqtt`. The json parser there is a little bit pesky on missing values in the processed json object.

**Comment by yp87** [comment]
Hello @sensor-freak,
Tobias' main repositories are in gitlab and changes are automatically mirrored to github. There is no reason for me to point to github over gitlab. So your MR is at the correct place in gitlab.

As for your MR here, I added some comments. I will approve it once they are fixed.

And for the timeToFull, I am not sure why I did this check in the first place. I removed it now.

Have a good day!

**Comment by sensor-freak** [comment]
Hello @yp87,

good to here that all (github/gitlab)

Regarding your comments to the MR: I couldn't find your comments, probably I'm looking in the wrong place. Can please give me a hint where are the comments so that I can work on them? (I've checked in my MR aka. pull request, but I couldn't see any comments.)

Thank you!

**Comment by yp87** [comment]
hello @sensor-freak,
oops, first time I comment on a PR in Github, I had to publish my review -_-'
