### ISSUE TITLE
Not connecting anymore

### ISSUE THREAD

**Issue by davc1** [yp87/leaf2mqtt#27]
I have an issue similar to #25. End of March I had a notification in the app that there was an upgrade. After that upgrade, your marvelous code stopped working. If I run the container, it says "An error occured while logging in". Of course the credentials are correct. 
I have a Leaf 2020, and everything worked fine up until this upgrade. I'm based in the UK.
My suspect is that they changed some API URL. I've asked Nissan, but they're not really cooperative.
I tried to delete and re-create everything from scratch, but no luck.

Any idea of what changed I guess on Nissan side.

Thanks, and keep up the good work for the community :)

**Comment by georgezip** [comment]
I had the same but deleted container, redownloaded from github, compiled and it is working now

**Comment by davc1** [comment]
Thanks. I did that already but it didn't work unfortunately.I'll try something else in the next few days.ThanksOn 26 Apr 2022 19:06, georgezip ***@***.***> wrote:
I had the same but deleted container, redownloaded from github, compiled and it is working now

**Comment by davc1** [comment]
I built a new server from scratch, and deployed this again from scratch, but still same issue. Credentials are fine of course. I've asked Nissan if they changed anything here in the UK for my model

**Comment by davc1** [comment]
It's working now, after I also reconfigured the MQTT broker on the Home Assistant. Just bizarre it stopped working after the Nissan app update as I never changed the MQTT broker config.
Thanks anyway for your help.

**Comment by yp87** [comment]
This outage was caused by Nissan. They changed the api key again, so the api access was broken until the new key was updated in Tobias' repository 6 days ago: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna/-/commit/45f5557057d3aa829b58647e87bc43cec9793d3f
