### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by guni12** [yp87/leaf2mqtt#29]
I've successfully managed to integrate leaf2mqtt into Home Assistant with this

https://community.home-assistant.io/t/nissan-leaf-component-s-platform/38663/638

but couldn't get all sensor values out.

When I downloaded MQTT-explorer I learned that this command:
leaf/{vin}/cockpitStatus/totalMileage

should be leaf/{vin}/cockpit/totalMileage

and now it works.

Thank you for letting us integrate the car into HA :-)

**Comment by yp87** [comment]
Hello,

I added the cockpitStatus message along cockpit for backward compatibility.

Thank you for reporting this!
