### ISSUE TITLE
Topics for the charging time with a time format instead of an integer

### ISSUE THREAD

**Issue by etricky** [yp87/leaf2mqtt#30]
Hello,

According to the documentation, the topics for the charging times like leaf/{vin}/battery/timeToFullL2InMinutes should return an integer representing minutes. However, the values I'm getting are not an integer but a time format to the nanosecond, for example, 10:00:00.000000. Which values and their format should these topics return, an integer or a time format?

![image](https://user-images.githubusercontent.com/6766415/168826589-1992741e-133d-4506-b217-82d60660f714.png)

**Comment by yp87** [comment]
Hello!
Thank you for reporting this. Looks like I got things mixed up when implementing that part. I will keep the `H:MM:SS.mmmmmm` format to ensure backward compatibility even if the field name contains `InMinutes`. I updated the readme to reflect that.

I will close this issue now, If you really need those values in minutes and cannot parse the `H:MM:SS.mmmmmm` format, re-open this issue, I will try to come up with something not too confusing for the users without breaking backward compatibility.
