### ISSUE TITLE
Container failing to start in HAOS 8.1, Core 2022.6.5

### ISSUE THREAD

**Issue by liquidphire** [yp87/leaf2mqtt#33]
Hello,

I just installed this add-on via Add-on Store (v39) as a custom repository and while the installation seems to have gone through fine, I am hitting a error when trying to start the add-on:

```
s6-overlay-suexec: fatal: can only run as pid 1
```
Some quick searching reveals this might be related to some HASS updates recently: 
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

I've noticed the add-on config is missing the `init: false` per the suggestion in the Dev Post. Of course I would absolutely be misunderstanding the issue, but I'm interesting in trying this addon out.

**Comment by guni12** [comment]
I tried this out and noticed that you are correct, suddenly it does not run after the install.

As a workaround you can install like this
https://community.home-assistant.io/t/nissan-leaf-component-s-platform/38663/638
and add the init: false line.

I just tested and it worked for me. (I uninstalled the added addon first ;-))

**Comment by yp87** [comment]
I updated the repo with init false. Please confirm if it works now

**Comment by liquidphire** [comment]
Hello!

I reinstalled the depot and it does seem to attempt to boot now, but gets stuck here:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Leaf2MQTT
 Interact with your Nissan Leaf using MQTT
-----------------------------------------------------------
 Add-on version: 39
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.6.5
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun leaf2mqtt (no readiness notification)
s6-supervise leaf2mqtt (child): fatal: unable to exec run: Permission denied
s6-supervise leaf2mqtt: warning: unable to spawn ./run - waiting 10 seconds
...
```
And the last two lines just repeat.

**Comment by yp87** [comment]
Missed a step in the link you provided, I update the repo again

**Comment by liquidphire** [comment]
Hi,

The service seems to be starting properly now, and is connecting to my MQTT server. However, I don't seem to be able to log into my Nissan Connect account and get this error:
```
WARNING: 2022-06-15 08:50:45.496: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
```

That said, I don't think this is related to the original issue so for what it's worth we can close this one out. Thanks for your help!
