### ISSUE TITLE
Several errors in log and some values not available

### ISSUE THREAD

**Issue by RalfPfitzner** [yp87/leaf2mqtt#36]
**Describe the bug**
I get several errors in the log:
`FINE: 2022-08-30 13:50:41.117918: LeafSession: FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^
FINER: 2022-08-30 13:50:41.118510: LeafSession: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:612)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      CarwingsSession.request (package:dartcarwings/src/carwings_session.dart:72)
<asynchronous suspension>
#7      CarwingsSession.requestWithRetry (package:dartcarwings/src/carwings_session.dart:46)
<asynchronous suspension>
#8      CarwingsVehicle.requestLocation (package:dartcarwings/src/carwings_vehicle.dart:355)
<asynchronous suspension>
#9      CarwingsVehicleWrapper.fetchLocation (file:///app/src/leaf/carwings_wrapper.dart:110)
<asynchronous suspension>
#10     LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#11     LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#13     startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#14     Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#15     main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>
FINE: 2022-08-30 13:50:41.118803: LeafSession: Exception: Execution failed.
FINER: 2022-08-30 13:50:41.119028: LeafSession: #0      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:161)
<asynchronous suspension>
#1      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#3      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#5      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>
WARNING: 2022-08-30 13:50:41.119089: main: Could not execute request.
FINEST: 2022-08-30 13:50:41.119166: MqttClientWrapper: Publishing message lastErrorDateTimeUtc 2022-08-30T11:50:41.119125Z
FINEST: 2022-08-30 13:50:41.119707: MqttClientWrapper: Publishing message {vin}/lastErrorDateTimeUtc 2022-08-30T11:50:41.119125Z
FINE: 2022-08-30 13:50:50.477278: LeafSession: Error
FINER: 2022-08-30 13:50:50.478189: LeafSession: #0      CarwingsVehicle.responseFlagHandler (package:dartcarwings/src/carwings_vehicle.dart:398)
#1      CarwingsVehicle._getCabinTemperature (package:dartcarwings/src/carwings_vehicle.dart:332)
<asynchronous suspension>
#2      CarwingsVehicle.requestCabinTemperature (package:dartcarwings/src/carwings_vehicle.dart:311)
<asynchronous suspension>
#3      CarwingsVehicleWrapper.fetchClimateStatus (file:///app/src/leaf/carwings_wrapper.dart:87)
<asynchronous suspension>
#4      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#5      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#7      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:521)
<asynchronous suspension>
#9      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>
FINER: 2022-08-30 13:50:50.478426: LeafSession: Force a login before retrying failed execution.
FINEST: 2022-08-30 13:50:58.301477: LeafSession: Executing`

The values for Status, Location and Cockpit Status are not fetched, Batterie and Climate are fine.

**LEAF_TYPE**
It's a European Leaf from 2018

**Expected behavior**
At least the values for Status and Cockpit Status should be available. Location is cancelled for Europe.

Thanks for the great work!!

**Comment by Krolykke** [comment]
Do you have anything working at all?

Most works for me (I have not tested all though), I get Status, Location and Cockpit Status fine but I struggle with leaf/battery/json and leaf/battery/capacity

**Comment by RalfPfitzner** [comment]
No, switched it off again.

**Comment by Krolykke** [comment]
@yp87 I guess you can close this.
