### ISSUE TITLE
Wrong VIN 

### ISSUE THREAD

**Issue by lowrisk75** [yp87/leaf2mqtt#37]
**Describe the bug**

Using leaf1mqtt for the first time, the VIN is not mine!
```
 [17:57:13] INFO: Starting leaf2mqtt...
INFO: 2022-08-30 17:57:13.292011: main: V0.11
INFO: 2022-08-30 17:57:13.292333: MqttClientWrapper: Creating MQTT client with 192.168.3.251:1883 listening on leaf.
INFO: 2022-08-30 17:57:13.292988: MqttClientWrapper: Connecting...
INFO: 2022-08-30 17:57:13.318601: MqttClientWrapper: Mqtt connection code: MqttConnectReturnCode.connectionAccepted
INFO: 2022-08-30 17:57:13.318689: main: Logging in.
INFO: 2022-08-30 17:57:22.118299: main: Login successful
INFO: 2022-08-30 17:57:22.118501: main: MQTT connected.
INFO: 2022-08-30 17:57:22.118551: MqttClientWrapper: Subscribing to command topics
INFO: 2022-08-30 17:57:22.121976: main: Starting loop for SJN###########
INFO: 2022-08-30 17:57:22.122549: main: Subscribing to commands for SJN###########
WARNING: 2022-08-30 17:57:44.191089: main: Could not execute request.

```
**LEAF_TYPE**
Nissan Leaf 24kw 2016 bought in ireland but moved to France (had to switch Nissan Plus account for remote service to work again)

**Expected behavior**
I would expect the normal VIN to showup, I didn't used leaf2mqtt before, I have the haos integration (nissan leaf) setup on my config files

**Comment by Krolykke** [comment]
I would think its a issue with your Nissan account. Does it work otherwise? Can you get any other data of that VIN like position?

What happens if you don't specify VIN? If you only have one leaf you don't have to as I understand it.

**Comment by lowrisk75** [comment]
> I would think its a issue with your Nissan account. Does it work otherwise? Can you get any other data of that VIN like position?
> 
> What happens if you don't specify VIN? If you only have one leaf you don't have to as I understand it.

It's seems that the VIN is correct now, weird because I don't remember doing anything ! anyway I still have the HAIO Nissan integration too and I don't really get how to play with leaf2mqtt, I'll try to find some documentations/ tutos
thank you.
