### ISSUE TITLE
An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.

### ISSUE THREAD

**Issue by nuno99costa** [yp87/leaf2mqtt#40]
**Describe the bug**
From yesterday onwards, I have not been able to connect to the Nissan Connect services

**LEAF_TYPE**
Newer than 2019 Nissan Leaf (Europe)

**Logs**
```

WARNING: 2022-10-20 09:12:37.858791: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
FINE: 2022-10-20 09:12:37.858865: main: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("data")
FINE: 2022-10-20 09:12:37.858950: main: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      NissanConnectSession.login (package:dartnissanconnect/src/nissanconnect_session.dart:319)
<asynchronous suspension>
#3      NissanConnectSessionWrapper.login (file:///app/src/leaf/nissan_connect_wrapper.dart:21)
<asynchronous suspension>
#4      _login (file:///app/src/leaf_2_mqtt.dart:87)
<asynchronous suspension>
#5      main (file:///app/src/leaf_2_mqtt.dart:63)
<asynchronous suspension>
WARNING: 2022-10-20 09:12:37.858965: main: Could not execute request.
FINEST: 2022-10-20 09:12:37.858984: MqttClientWrapper: Publishing message lastErrorDateTimeUtc 2022-10-20T09:12:37.858978Z
```

**Comment by nuno99costa** [comment]
I have tried recreating, rebuilding and rebooting the container and host, but no success.

**Comment by atxbyea** [comment]
Nissan had maintenance last night, this is probably related and might have changed something in how the login process happens

**Comment by phairplay** [comment]
Hi,
I've just taken delivery of the new 22 leaf and can confirm I'm seeing the same issue when I installed this app. I'm able to log in without issue on the app. is there a possible fix?

**Comment by RobertRoxenhall** [comment]
Nissan Leaf 2021 here with the same issue.

**Comment by RobertRoxenhall** [comment]
Okay after some googling they've updated something. Check [here](https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e7a78e85247512e50a92970da77968c5fa1ee43a) for more information.

**Comment by yp87** [comment]
Updated to newest version, however, the cockpit function to get total mileage is now broken since it used an unofficial library that is not yet updated with the fix.
@sensor-freak, can you merge from the official lib please?

**Comment by yp87** [comment]
@nuno99costa Unless you change something in the code, there is no point in rebuilding the container if you use `yp87/leaf2mqtt` as the container image. You will only need to pull the new one when the code on this repository change (the image is published automatically)

**Comment by sensor-freak** [comment]
> Updated to newest version, however, the cockpit function to get total mileage is now broken since it used an unofficial library that is not yet updated with the fix. @sensor-freak, can you merge from the official lib please?

I've merged my fork with the latest changes and also updated all packages to latest versions. My fork is also using a slightly modified fork of the `dartnissanconnect` package - that's probably the unofficial library your speaking of?

However, since I'm only a casual Dart developer, I'm not quite sure what I've done to make it work again (except for merging the login changes from here).

**Comment by sensor-freak** [comment]
If someone is curious: The modified library is hosted somewhere else: https://gitlab.com/sensor-freak/dartnissanconnect

**Comment by yp87** [comment]
Thank you @sensor-freak, I now point to your version again.
