### ISSUE TITLE
Still seeing the "main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds." error

### ISSUE THREAD

**Issue by RyanAtTanagra** [yp87/leaf2mqtt#44]
Still seeing this exact error:
https://github.com/yp87/leaf2mqtt/issues/40

**LEAF_TYPE**
2023 SV Plus in the US (newerThanMay2019)

HA is showing current version 44, but running Hassio so not sure how to verify code changes (still new to HA), so could very well be on my end.

First time setting up so I may have something set up wrong, but quadruple checked user/pass.  Does it have any issues with special chars in the password field?

**Comment by RyanAtTanagra** [comment]
Removed the special char from my password, so it's not that.  Also should have added it's also getting this after the bad user/pass/type line, like the previous issue:

main: NoSuchMethodError: The method '[]' was called on null.

Also confirmed in the logs it's running 44
Add-on version: 44
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2

**Comment by yp87** [comment]
Hello @RyanAtTanagra, Leaf2Mqtt is based on My Leaf's libraries.
Can you try the My Leaf app? If it doesn't work with it then it won't work with leaf2mqtt
Android: https://play.google.com/store/apps/details?id=dk.kjeldsen.carwingsflutter&hl=en_CA&gl=US&pli=1
IOS: https://apps.apple.com/be/app/my-leaf-for-nissan-ev/id1436701776

**Comment by RyanAtTanagra** [comment]
Can't sign in, and the app has a warning:
"To all NA users, Nissan of North America has blocked My Leaf and other clients"

So that's a bummer....

**Comment by yp87** [comment]
Did you try different regions?

If none work than it won't work with Leaf2mqtt unfortunately.

**Comment by RyanAtTanagra** [comment]
Yea unfortunately not, fails with any region.  Well, not a Leaf2MQTT issue then, feel free to close this.  Thanks for helping narrow down the cause.  Hopefully My Leaf figures out o workaround or Nissan of NA gets their heads out of their butts and stops fighting against their customers' wishes.
