### ISSUE TITLE
An error occured while logging in.

### ISSUE THREAD

**Issue by drdystopia** [yp87/leaf2mqtt#46]
**Describe the bug**
Error: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.

In USA - 2021 Lead S+ Log in on Nissan Website and App work. 

Uninstalled MQTT and Add-on multiple times over the last few days as well as reset Nissan password. New password works on Nissan Site, NissanConnect EV Android App, Nissan Connect Android App, and MyNissan Android app.

Using newerThanMay2019

also tried old USA for the hell of it and that didnt work either.

**LEAF_TYPE**
newerThanMay2019

**Expected behavior**
connecting to nissan connect

**Comment by hkapanen** [comment]
See https://tobis.dk/blog/the-farce-of-nissanconnect-north-america/

**Comment by yp87** [comment]
Does it work if you use the My Leaf app?
