### ISSUE TITLE
Nissan Ariya

### ISSUE THREAD

**Issue by tobiasbrage** [yp87/leaf2mqtt#48]
Hi, I've integrated your add-on and it spits out information. The issue though is that I only recieve very basic information such as mileage and cabin temperature. No battery information at all which is kind of the point with an EV.
We have a Nissan Ariya and the integration clearly is made for a Leaf but maybe it can be modified to support the Ariya as well?

**Comment by vinta7** [comment]
Hi, leaf2mqtt is working but need information about battery, so it would be great with Nissan Ariya support.

**Comment by tobiasbrage** [comment]
What information are you getting? I'm getting canin temperature, ignition, mileage and stuff like that. Only battery related data is missing like battery percentage and mileage.> Hi, leaf2mqtt is working but need information about battery, so it would be great with Nissan Ariya support.

**Comment by vinta7** [comment]
Some of the same, also geo location, vin number, set the nickname to 'Ariya 1'

**Comment by yp87** [comment]
Hello, this app is based on the libraries used by My Leaf app. Do you have more functionality with this app with your Ariya?

**Comment by tobiasbrage** [comment]
Sadly I can't tell you. I've never owned a Nissan before so I can't compare different Nissan apps against each other. > Hello, this app is based on the libraries used by My Leaf app. Do you have more functionality with this app with your Ariya?

**Comment by vinta7** [comment]
Hi, I am also using the NissanConnect app, attached is the log file from the latest build, I changed the vin number and geo location.
Regards

[full_log.txt](https://github.com/yp87/leaf2mqtt/files/10880687/full_log.txt)

**Comment by rick2909** [comment]
To help the  My Leaf app also shows this basic information. so no battery info and such.

**Comment by yp87** [comment]
Leaf2Mqtt will have the same limitations as the My Leaf app (unofficial leaf app) since it uses the same libraries.
Please ask the owner of My Leaf app to add support for Ariya so it can then also work with Leaf2mqtt. Sorry, I cannot do anything more for this.
