### ISSUE TITLE
leaf/battery/connected and leaf/battery/charging booleans not updating

### ISSUE THREAD

**Issue by henripalmroth** [yp87/leaf2mqtt#49]
**Describe the bug**
Thanks for the great add-on! Have been running it for a while and it looks like everything else is updating as expected but not the boolean values like leaf/battery/connected and leaf/battery/charging. No matter if I'm trying to update only battery or "all" multiple times. After opening Nissan Connect app and updating car status those are updated properly to leaf2mqtt. Just wondering are we missing some specific update endpoint? edit: also I'm not using VIN codes in topics. Just having one Leaf.

**LEAF_TYPE**
newerThanMay2019 (Leaf 2020 40 kwh)

**Expected behavior**
leaf/battery/connected and leaf/battery/charging are updating after battery update or "all" update is called.

**Comment by yp87** [comment]
Does it work with the My Leaf app? Leaf2Mqtt uses the same libraries.
If it does not work then you can contact the owner of the app. Else, there is not much I can do since the api used by my car is now blocked by Nissan so I cannot test anything.

**Comment by henripalmroth** [comment]
Ok, thanks anyway! Haven't tried My Leaf app.
