### ISSUE TITLE
Unable to build image due Dart SDK null safety issue

### ISSUE THREAD

**Issue by mif11k** [yp87/leaf2mqtt#52]
I try to build the image on Raspberry 4, but I get this error. Does the code have to be updated or can I do something about is on my side?

=> ERROR [build 5/8] RUN dart pub get                                                                                                                      2.1s
------
 > [build 5/8] RUN dart pub get:
#0 1.796 Resolving dependencies...
#0 1.859 The lower bound of "sdk: '>=2.10.0 <3.0.0'" must be 2.12.0'
#0 1.860 or higher to enable null safety.
#0 1.860
#0 1.860 The current Dart SDK (3.0.1) only supports null safety.
#0 1.860
#0 1.860 For details, see https://dart.dev/null-safety
------
failed to solve: process "/bin/sh -c dart pub get" did not complete successfully: exit code: 65

**Comment by yp87** [comment]
Updated dockerfile to fix the sdk version. Should work now if you build in docker

**Comment by mif11k** [comment]
> Updated dockerfile to fix the sdk version. Should work now if you build in docker

Thanks, building woks now!
