### ISSUE TITLE
Support non-North America leaf made before May 2019

### ISSUE THREAD

**Issue by yp87** [yp87/leaf2mqtt#6]
Add [DartCarwings library](https://github.com/Tobiaswk/carwingsflutter) support.

**Comment by yp87** [comment]
Missing blowfish implementation

**Comment by yp87** [comment]
Enabled support since blowish was added directly in the DartCarwings library.

**Comment by tskulbru** [comment]
I couldnt get this to work, what exactly do I use as LEAF_TYPE to get this working?

**Comment by yp87** [comment]
Hello @tskulbru !
I forgot to update the readme 😅
Here are the new choices: `olderEurope`,  `olderAustralia` or `olderJapan`.
I could not test it because I am not from these region, so I am re-opening this issue until I receive your feedback.

Thank you!

**Comment by tskulbru** [comment]
Can confirm olderEurope works for my 2018 Leaf.

**Comment by yp87** [comment]
Awesome!
