### ISSUE TITLE
ARM support (Raspberry Pi)

### ISSUE THREAD

**Issue by l3nticular** [yp87/leaf2mqtt#7]
The google/dart image doesn't support ARM architectures such as Raspberry Pi.

I don't see a really quick solution; the dart-arm images that I was able to find could complete the image build with some modifications, but still failed to execute.

**Comment by l3nticular** [comment]
I seem to have gotten something working on my fork

**Comment by yp87** [comment]
Great! If you want you can merge it here. 
If you decide to do so, please put x86 as the default to prevent breaking other users.

also create 2 docker-compose files (.x86.yaml & .arm.yaml which extends x86 by replacing the dockerfile path

Thank you!
