### ISSUE TITLE
Fresh build no longer connects to NissanConnect

### ISSUE THREAD

**Issue by haberda** [yp87/leaf2mqtt#9]
There seems to have been an API change on that requires an update to connect successfully. I am guessing that [this](https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna) is the upstream. That project seems to have had a recent update to fix the API issue. I don't know really anything about Dart, I tried to fix it myself but got nowhere.

I tried removing the container and image and rebuilding (hence my PR) in the hopes it would pull dependencies from upstream, but that unfortunately didn't work.

**Comment by yp87** [comment]
Hello @haberda ,

Sorry for the delay, I updated the packages to their latest versions.

For your information, you need to run `dart pub upgrade` in order to update the pubspec.lock file to the latest commit ids for these packages.

Thank you!
